NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.sell.trace.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.sell.trace.com-cert.pem
    OrganizationalUnitIdentifier: peer
